services:
    mariadb:
        container_name: web-mariadb-2
        hostname: mariadb
        image: mariadb:10.5
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIADB_DATABASE: 2-WebCalculatorDb
            MARIADB_USER: root
            MARIADB_PASSWORD: password
        ports:
            - "0.0.0.0:5032:3306"

    web:
        container_name: web-app-calculator-2
        hostname: app
        build: .
        ports:
            - "0.0.0.0:5002:5002"